name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 11 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Pod Installation
        run: pod install
      - name: Build
        run: |
          xcodebuild clean build -workspace SRSNetwork.xcworkspace -scheme SRSNetwork -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -workspace SRSNetwork.xcworkspace -scheme SRSNetworkTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
